
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_HIGHLIGHT = 'FETCH_HIGHLIGHT';
export const CURRENT_HIGHLIGHT = 'CURRENT_HIGHLIGHT';
export const CURRENT_POST = 'CURRENT_POST';
export const CURRENT_POPOVERBOX = 'CURRENT_POPOVERBOX';
